# Generated by Django 5.1.15 on 2026-05-02 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("content_body", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("article", "Article"), ("podcast", "Podcast")],
                        max_length=16,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("text", "Text"),
                            ("pdf", "PDF"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("media_url", models.CharField(blank=True, max_length=512, null=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        db_column="author_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contents",
                "ordering": ["-created_at"],
            },
        ),
    ]
