# Generated by Django 5.1.15 on 2026-05-02 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_date", models.DateTimeField(auto_now_add=True)),
                (
                    "certificate_url",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "verification_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        db_column="course_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "certificates",
                "ordering": ["-issue_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "course"), name="uq_user_course_certificate"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_lessons", models.JSONField(blank=True, default=list)),
                ("completed_sections", models.JSONField(blank=True, default=list)),
                ("test_attempts", models.JSONField(blank=True, default=list)),
                ("test_scores", models.JSONField(blank=True, default=list)),
                (
                    "course",
                    models.ForeignKey(
                        db_column="course_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "enrollments",
                "ordering": ["-enrolled_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "course"), name="uq_enrollment_user_course"
                    )
                ],
            },
        ),
    ]
