# In backend/app/permissions/permission_definitions.py
ROLES_PERMISSIONS_DATA = {
    'super_admin': [
        {'permission': 'create_user', 'title': 'Create User', 'category': 'User Management'},
        {'permission': 'view_any_user', 'title': 'View Any User Profile', 'category': 'User Management'},
        {'permission': 'edit_any_user', 'title': 'Edit Any User Profile', 'category': 'User Management'},
        {'permission': 'delete_any_user', 'title': 'Delete Any User', 'category': 'User Management'},
        {'permission': 'view_own_profile', 'title': 'View Own Profile', 'category': 'User Management'},
        {'permission': 'edit_own_profile', 'title': 'Edit Own Profile', 'category': 'User Management'},
        {'permission': 'create_role', 'title': 'Create Role', 'category': 'Role Management'},
        {'permission': 'view_role', 'title': 'View Role', 'category': 'Role Management'},
        {'permission': 'edit_role', 'title': 'Edit Role', 'category': 'Role Management'},
        {'permission': 'delete_role', 'title': 'Delete Role', 'category': 'Role Management'},
        {'permission': 'assign_permission_to_role', 'title': 'Assign Permission to Role', 'category': 'Role Management'},
        {'permission': 'remove_permission_from_role', 'title': 'Remove Permission from Role', 'category': 'Role Management'},
        {'permission': 'create_permission_def', 'title': 'Create Permission Definition', 'category': 'Permission Definition Management'},
        {'permission': 'view_permission_def', 'title': 'View Permission Definition', 'category': 'Permission Definition Management'},
        {'permission': 'edit_permission_def', 'title': 'Edit Permission Definition', 'category': 'Permission Definition Management'},
        {'permission': 'delete_permission_def', 'title': 'Delete Permission Definition', 'category': 'Permission Definition Management'},
        {'permission': 'assign_user_permission_override', 'title': 'Assign User Permission Override', 'category': 'User Permission Overrides'},
        {'permission': 'view_user_permission_override', 'title': 'View User Permission Override', 'category': 'User Permission Overrides'},
        {'permission': 'remove_user_permission_override', 'title': 'Remove User Permission Override', 'category': 'User Permission Overrides'},
        {'permission': 'create_course', 'title': 'Create Course', 'category': 'Course Management'},
        {'permission': 'view_any_course', 'title': 'View Any Course', 'category': 'Course Management'},
        {'permission': 'edit_any_course', 'title': 'Edit Any Course', 'category': 'Course Management'},
        {'permission': 'delete_any_course', 'title': 'Delete Any Course', 'category': 'Course Management'},
        {'permission': 'enroll_in_course', 'title': 'Enroll in Course', 'category': 'Course Enrollment'},
        {'permission': 'view_own_enrolled_courses', 'title': 'View Own Enrolled Courses', 'category': 'Course Enrollment'},
        {'permission': 'manage_course_content', 'title': 'Manage Course Content (Lessons, Sections)', 'category': 'Course Structure'},
        {'permission': 'view_course_content', 'title': 'View Course Content', 'category': 'Course Content'},
        {'permission': 'create_content', 'title': 'Create Content', 'category': 'Content Management'},
        {'permission': 'view_content', 'title': 'View Content', 'category': 'Content Management'},
        {'permission': 'edit_content', 'title': 'Edit Content', 'category': 'Content Management'},
        {'permission': 'delete_content', 'title': 'Delete Content', 'category': 'Content Management'},
        {'permission': 'view_any_content', 'title': 'View Any Content (Published)', 'category': 'Content Management'},
        {'permission': 'view_own_content', 'title': 'View Own Content (Drafts & Published)', 'category': 'Content Management'},
        {'permission': 'edit_own_content', 'title': 'Edit Own Content', 'category': 'Content Management'},
        {'permission': 'delete_own_content', 'title': 'Delete Own Content', 'category': 'Content Management'},
        {'permission': 'publish_own_content', 'title': 'Publish Own Content', 'category': 'Content Management'},
        {'permission': 'view_any_course_listing', 'title': 'View Any Course Listing (Published)', 'category': 'Course Management'},
        {'permission': 'view_course_detail', 'title': 'View Course Detail', 'category': 'Course Management'},
        {'permission': 'edit_own_course', 'title': 'Edit Own Course', 'category': 'Course Management'},
        {'permission': 'delete_own_course', 'title': 'Delete Own Course', 'category': 'Course Management'},
        {'permission': 'publish_course', 'title': 'Publish/Unpublish Course', 'category': 'Course Management'},
        {'permission': 'create_course_section', 'title': 'Create Course Section', 'category': 'Course Structure'},
        {'permission': 'view_course_sections', 'title': 'View Course Sections', 'category': 'Course Structure'},
        {'permission': 'view_course_section_detail', 'title': 'View Course Section Detail', 'category': 'Course Structure'},
        {'permission': 'edit_course_section', 'title': 'Edit Course Section', 'category': 'Course Structure'},
        {'permission': 'delete_course_section', 'title': 'Delete Course Section', 'category': 'Course Structure'},
        {'permission': 'create_course_lesson', 'title': 'Create Course Lesson', 'category': 'Course Content'},
        {'permission': 'view_course_lessons', 'title': 'View Course Lessons', 'category': 'Course Content'},
        {'permission': 'view_course_lesson_detail', 'title': 'View Course Lesson Detail', 'category': 'Course Content'},
        {'permission': 'edit_course_lesson', 'title': 'Edit Course Lesson', 'category': 'Course Content'},
        {'permission': 'delete_course_lesson', 'title': 'Delete Course Lesson', 'category': 'Course Content'},
        {'permission': 'create_course_test', 'title': 'Create Course Test', 'category': 'Course Assessment'},
        {'permission': 'view_course_test', 'title': 'View Course Test', 'category': 'Course Assessment'},
        {'permission': 'edit_course_test', 'title': 'Edit Course Test', 'category': 'Course Assessment'},
        {'permission': 'delete_course_test', 'title': 'Delete Course Test', 'category': 'Course Assessment'},
        {'permission': 'create_test_question', 'title': 'Create Test Question', 'category': 'Course Assessment'},
        {'permission': 'view_test_questions', 'title': 'View Test Questions', 'category': 'Course Assessment'},
        {'permission': 'edit_test_question', 'title': 'Edit Test Question', 'category': 'Course Assessment'},
        {'permission': 'delete_test_question', 'title': 'Delete Test Question', 'category': 'Course Assessment'},
        {'permission': 'unenroll_from_course', 'title': 'Unenroll from Course', 'category': 'Course Enrollment'},
        {'permission': 'view_own_instructed_courses', 'title': 'View Own Instructed Courses', 'category': 'Course Management'},
        {'permission': 'create_live_session', 'title': 'Create Live Session', 'category': 'Live Sessions'},
        {'permission': 'view_live_sessions_for_course', 'title': 'View Live Sessions for Course', 'category': 'Live Sessions'},
        {'permission': 'view_live_session_detail', 'title': 'View Live Session Detail', 'category': 'Live Sessions'},
        {'permission': 'edit_live_session', 'title': 'Edit Live Session', 'category': 'Live Sessions'},
        {'permission': 'delete_live_session', 'title': 'Delete Live Session', 'category': 'Live Sessions'},
        {'permission': 'view_any_user_profile_detail', 'title': 'View Any User Profile Detail', 'category': 'User Management'},
        {'permission': 'edit_any_user_profile_detail', 'title': 'Edit Any User Profile Detail', 'category': 'User Management'},
        {'permission': 'manage_professor_profiles', 'title': 'Manage Professor Profiles', 'category': 'User Management'}
    ],
    'admin': [
        {'permission': 'view_own_profile', 'title': 'View Own Profile', 'category': 'User Management'},
        {'permission': 'edit_own_profile', 'title': 'Edit Own Profile', 'category': 'User Management'},
        {'permission': 'manage_own_account', 'title': 'Manage Own Account', 'category': 'User Management'},
        {'permission': 'create_user', 'title': 'Create User', 'category': 'User Management'},
        {'permission': 'delete_any_user', 'title': 'Delete Any User', 'category': 'User Management'},
        {'permission': 'view_any_user', 'title': 'View Any User Profile', 'category': 'User Management'},
        {'permission': 'edit_any_user', 'title': 'Edit Any User Profile', 'category': 'User Management'},
        {'permission': 'view_role', 'title': 'View Role', 'category': 'Role Management'},
        {'permission': 'assign_permission_to_role', 'title': 'Assign Permission to Role', 'category': 'Role Management'},
        {'permission': 'remove_permission_from_role', 'title': 'Remove Permission from Role', 'category': 'Role Management'},
        {'permission': 'view_permission_def', 'title': 'View Permission Definition', 'category': 'Permission Definition Management'},
        {'permission': 'view_any_course', 'title': 'View Any Course', 'category': 'Course Management'},
        {'permission': 'assign_user_permission_override', 'title': 'Assign User Permission Override', 'category': 'User Permission Overrides'},
        {'permission': 'view_user_permission_override', 'title': 'View User Permission Override', 'category': 'User Permission Overrides'},
        {'permission': 'remove_user_permission_override', 'title': 'Remove User Permission Override', 'category': 'User Permission Overrides'},
        {'permission': 'view_any_content', 'title': 'View Any Content (Published & Drafts)', 'category': 'Content Management'},
        {'permission': 'publish_course', 'title': 'Publish/Unpublish Any Course', 'category': 'Course Management'},
        {'permission': 'view_course_detail', 'title': 'View Course Detail (Any)', 'category': 'Course Management'},
        {'permission': 'view_course_sections', 'title': 'View Course Sections (Any)', 'category': 'Course Structure'},
        {'permission': 'view_course_lessons', 'title': 'View Course Lessons (Any)', 'category': 'Course Content'},
        {'permission': 'view_course_test', 'title': 'View Course Test (Any)', 'category': 'Course Assessment'},
        {'permission': 'view_any_user_profile_detail', 'title': 'View Any User Profile Detail', 'category': 'User Management'},
        {'permission': 'edit_any_user_profile_detail', 'title': 'Edit Any User Profile Detail', 'category': 'User Management'},
        {'permission': 'view_live_sessions_for_course', 'title': 'View Live Sessions for Any Course', 'category': 'Live Sessions'},
        {'permission': 'view_live_session_detail', 'title': 'View Any Live Session Detail', 'category': 'Live Sessions'},
        {'permission': 'edit_any_course', 'title': 'Edit Any Course (Metadata, Status)', 'category': 'Course Management'},
        {'permission': 'delete_any_course', 'title': 'Delete Any Course', 'category': 'Course Management'},
        {'permission': 'manage_course_content', 'title': 'Manage Course Content (Any Course)', 'category': 'Course Structure'},
        {'permission': 'edit_content', 'title': 'Edit Any Content', 'category': 'Content Management'},
        {'permission': 'delete_content', 'title': 'Delete Any Content', 'category': 'Content Management'},
        {'permission': 'edit_live_session', 'title': 'Edit Any Live Session', 'category': 'Live Sessions'},
        {'permission': 'delete_live_session', 'title': 'Delete Any Live Session', 'category': 'Live Sessions'},
        {'permission': 'manage_professor_profiles', 'title': 'Manage Professor Profiles', 'category': 'User Management'},
        {'permission': 'edit_course_lesson', 'title': 'Edit Course Lesson (Own Course)', 'category': 'Course Content'}
    ],
    'professor': [
        {'permission': 'view_own_profile', 'title': 'View Own Profile', 'category': 'User Management'},
        {'permission': 'edit_own_profile', 'title': 'Edit Own Profile', 'category': 'User Management'},
        {'permission': 'create_course', 'title': 'Create Course', 'category': 'Course Management'},
        {'permission': 'manage_course_content', 'title': 'Manage Course Content (Lessons, Sections)', 'category': 'Course Structure'},
        {'permission': 'view_course_content', 'title': 'View Course Content', 'category': 'Course Content'},
        {'permission': 'view_own_enrolled_courses', 'title': 'View Own Enrolled Courses', 'category': 'Course Enrollment'},
        {'permission': 'view_own_content', 'title': 'View Own Content (Drafts & Published)', 'category': 'Content Management'},
        {'permission': 'edit_own_content', 'title': 'Edit Own Content', 'category': 'Content Management'},
        {'permission': 'delete_own_content', 'title': 'Delete Own Content', 'category': 'Content Management'},
        {'permission': 'publish_own_content', 'title': 'Publish Own Content', 'category': 'Content Management'},
        {'permission': 'edit_own_course', 'title': 'Edit Own Course', 'category': 'Course Management'},
        {'permission': 'delete_own_course', 'title': 'Delete Own Course', 'category': 'Course Management'},
        {'permission': 'publish_course', 'title': 'Publish/Unpublish Own Course', 'category': 'Course Management'},
        {'permission': 'view_course_detail', 'title': 'View Course Detail (Published & Enrolled)', 'category': 'Course Management'},
        {'permission': 'create_course_section', 'title': 'Create Course Section (Own Course)', 'category': 'Course Structure'},
        {'permission': 'view_course_sections', 'title': 'View Course Sections (Own & Published)', 'category': 'Course Structure'},
        {'permission': 'view_course_section_detail', 'title': 'View Course Section Detail (Own & Published)', 'category': 'Course Structure'},
        {'permission': 'edit_course_section', 'title': 'Edit Course Section (Own Course)', 'category': 'Course Structure'},
        {'permission': 'delete_course_section', 'title': 'Delete Course Section (Own Course)', 'category': 'Course Structure'},
        {'permission': 'create_course_lesson', 'title': 'Create Course Lesson (Own Course)', 'category': 'Course Content'},
        {'permission': 'view_course_lessons', 'title': 'View Course Lessons (Own & Published)', 'category': 'Course Content'},
        {'permission': 'view_course_lesson_detail', 'title': 'View Course Lesson Detail (Own & Published)', 'category': 'Course Content'},
        {'permission': 'edit_course_lesson', 'title': 'Edit Course Lesson (Own Course)', 'category': 'Course Content'},
        {'permission': 'delete_course_lesson', 'title': 'Delete Course Lesson (Own Course)', 'category': 'Course Content'},
        {'permission': 'create_course_test', 'title': 'Create Course Test (Own Course)', 'category': 'Course Assessment'},
        {'permission': 'view_course_test', 'title': 'View Course Test (Own & Published)', 'category': 'Course Assessment'},
        {'permission': 'edit_course_test', 'title': 'Edit Course Test (Own Course)', 'category': 'Course Assessment'},
        {'permission': 'delete_course_test', 'title': 'Delete Course Test (Own Course)', 'category': 'Course Assessment'},
        {'permission': 'create_test_question', 'title': 'Create Test Question (Own Test)', 'category': 'Course Assessment'},
        {'permission': 'view_test_questions', 'title': 'View Test Questions (Own Test & Published)', 'category': 'Course Assessment'},
        {'permission': 'edit_test_question', 'title': 'Edit Test Question (Own Test)', 'category': 'Course Assessment'},
        {'permission': 'delete_test_question', 'title': 'Delete Test Question (Own Test)', 'category': 'Course Assessment'},
        {'permission': 'view_own_instructed_courses', 'title': 'View Own Instructed Courses', 'category': 'Course Management'},
        {'permission': 'create_live_session', 'title': 'Create Live Session (Own Course)', 'category': 'Live Sessions'},
        {'permission': 'view_live_sessions_for_course', 'title': 'View Live Sessions (Own & Published Courses)', 'category': 'Live Sessions'},
        {'permission': 'view_live_session_detail', 'title': 'View Live Session Detail (Own & Published)', 'category': 'Live Sessions'},
        {'permission': 'edit_live_session', 'title': 'Edit Live Session (Own Course)', 'category': 'Live Sessions'},
        {'permission': 'delete_live_session', 'title': 'Delete Live Session (Own Course)', 'category': 'Live Sessions'},
        {'permission': 'view_any_course_listing', 'title': 'View Any Course Listing (Published)', 'category': 'Course Management'},
        {'permission': 'view_any_content', 'title': 'View Any Content (Published)', 'category': 'Content Management'}
    ],
    'student': [
        {'permission': 'view_own_profile', 'title': 'View Own Profile', 'category': 'User Management'},
        {'permission': 'edit_own_profile', 'title': 'Edit Own Profile', 'category': 'User Management'},
        {'permission': 'enroll_in_course', 'title': 'Enroll in Course', 'category': 'Course Enrollment'},
        {'permission': 'view_own_enrolled_courses', 'title': 'View Own Enrolled Courses', 'category': 'Course Enrollment'},
        {'permission': 'view_course_content', 'title': 'View Course Content', 'category': 'Course Content'},
        {'permission': 'view_any_content', 'title': 'View Any Content (Published)', 'category': 'Content Management'},
        {'permission': 'view_course_detail', 'title': 'View Course Detail (Published & Enrolled)', 'category': 'Course Management'},
        {'permission': 'view_course_sections', 'title': 'View Course Sections (Enrolled)', 'category': 'Course Structure'},
        {'permission': 'view_course_lessons', 'title': 'View Course Lessons (Enrolled)', 'category': 'Course Content'},
        {'permission': 'view_course_test', 'title': 'View Course Test (Enrolled)', 'category': 'Course Assessment'},
        {'permission': 'unenroll_from_course', 'title': 'Unenroll from Course', 'category': 'Course Enrollment'},
        {'permission': 'view_live_sessions_for_course', 'title': 'View Live Sessions for Course (Enrolled/Published)', 'category': 'Live Sessions'},
        {'permission': 'view_live_session_detail', 'title': 'View Live Session Detail (Enrolled/Published)', 'category': 'Live Sessions'},
        {'permission': 'view_test_questions', 'title': 'View Test Questions (Enrolled Test)', 'category': 'Course Assessment'},
        {'permission': 'view_any_course_listing', 'title': 'View Any Course Listing (Published)', 'category': 'Course Management'},
        {'permission': 'edit_course_lesson', 'title': 'Edit Course Lesson (Own Course)', 'category': 'Course Content'}
    ]
}
