export const countries = [
  "Afghanistan",
  "Afrique du Sud",
  "Albanie",
  "Algérie",        // Déjà présent
  "Allemagne",
  "Andorre",
  "Angola",
  "Antigua-et-Barbuda",
  "Arabie Saoudite",
  "Argentine",
  "Arménie",
  "Australie",
  "Autriche",
  "Azerbaïdjan",
  "Bahamas",
  "Bahreïn",
  "Bangladesh",
  "Barbade",
  "Belgique",       // Déjà présent
  "Belize",
  "Bénin",
  "Bhoutan",
  "Biélorussie",
  "Birmanie",
  "Bolivie",
  "Bosnie-Herzégovine",
  "Botswana",
  "Brésil",
  "Brunei",
  "Bulgarie",
  "Burkina Faso",
  "Burundi",
  "Cambodge",
  "Cameroun",       // Déjà présent
  "Canada",         // Déjà présent
  "Cap-Vert",
  "Chili",
  "Chine",
  "Chypre",
  "Colombie",
  "Comores",
  "Congo (République démocratique du)", // RDC
  "Congo (République du)",            // Congo-Brazzaville
  "Corée du Nord",
  "Corée du Sud",
  "Costa Rica",
  "Côte d'Ivoire",  // Déjà présent
  "Croatie",
  "Cuba",
  "Danemark",
  "Djibouti",
  "Dominique",
  "Égypte",
  "Émirats arabes unis",
  "Équateur",
  "Érythrée",
  "Espagne",
  "Estonie",
  "Eswatini",
  "États-Unis",
  "Éthiopie",
  "Fidji",
  "Finlande",
  "France",         // Déjà présent
  "Gabon",
  "Gambie",
  "Géorgie",
  "Ghana",
  "Grèce",
  "Grenade",
  "Guatemala",
  "Guinée",
  "Guinée équatoriale",
  "Guinée-Bissau",
  "Guyana",
  "Haïti",
  "Honduras",
  "Hongrie",
  "Inde",
  "Indonésie",
  "Irak",
  "Iran",
  "Irlande",
  "Islande",
  "Israël",
  "Italie",
  "Jamaïque",
  "Japon",
  "Jordanie",
  "Kazakhstan",
  "Kenya",
  "Kirghizistan",
  "Kiribati",
  "Koweït",
  "Laos",
  "Lesotho",
  "Lettonie",
  "Liban",
  "Libéria",
  "Libye",
  "Liechtenstein",
  "Lituanie",
  "Luxembourg",
  "Macédoine du Nord",
  "Madagascar",
  "Malaisie",
  "Malawi",
  "Maldives",
  "Mali",           // Déjà présent
  "Malte",
  "Maroc",          // Déjà présent
  "Marshall (Îles)",
  "Maurice",
  "Mauritanie",
  "Mexique",
  "Micronésie",
  "Moldavie",
  "Monaco",
  "Mongolie",
  "Monténégro",
  "Mozambique",
  "Namibie",
  "Nauru",
  "Népal",
  "Nicaragua",
  "Niger",
  "Nigéria",
  "Niue",
  "Norvège",
  "Nouvelle-Zélande",
  "Oman",
  "Ouganda",
  "Ouzbékistan",
  "Pakistan",
  "Palaos",
  "Palestine",
  "Panama",
  "Papouasie-Nouvelle-Guinée",
  "Paraguay",
  "Pays-Bas",
  "Pérou",
  "Philippines",
  "Pologne",
  "Portugal",
  "Qatar",
  "République centrafricaine",
  "République dominicaine",
  "République tchèque",
  "Roumanie",
  "Royaume-Uni",
  "Russie",
  "Rwanda",
  "Saint-Christophe-et-Niévès",
  "Saint-Marin",
  "Saint-Vincent-et-les-Grenadines",
  "Sainte-Lucie",
  "Salomon (Îles)",
  "Salvador",
  "Samoa",
  "Sao Tomé-et-Principe",
  "Sénégal",        // Déjà présent
  "Serbie",
  "Seychelles",
  "Sierra Leone",
  "Singapour",
  "Slovaquie",
  "Slovénie",
  "Somalie",
  "Soudan",
  "Soudan du Sud",
  "Sri Lanka",
  "Suède",
  "Suisse",         // Déjà présent
  "Suriname",
  "Syrie",
  "Tadjikistan",
  "Tanzanie",
  "Tchad",
  "Thaïlande",
  "Timor oriental",
  "Togo",
  "Tonga",
  "Trinité-et-Tobago",
  "Tunisie",        // Déjà présent
  "Turkménistan",
  "Turquie",
  "Tuvalu",
  "Ukraine",
  "Uruguay",
  "Vanuatu",
  "Vatican",
  "Venezuela",
  "Viêt Nam",
  "Yémen",
  "Zambie",
  "Zimbabwe"
];

export const specializations = [
  'Développement Web',
  'Développement Mobile',
  'Marketing Digital',
  'Design Graphique',
  'Design UX/UI',
  'Business Administration / Gestion d\'Entreprise',
  'Finance / Comptabilité',
  'Langues Étrangères / Traduction / Interprétation',
  'Data Science / Analyse de Données',
  'Intelligence Artificielle / Machine Learning',
  'Cybersécurité',
  'Gestion de Projet',
  'Ressources Humaines',
  'Droit (général, des affaires, social, etc.)',
  'Communication / Relations Publiques',
  'Journalisme / Médias',
  'Éducation / Pédagogie / Ingénierie Pédagogique',
  'Santé Publique',
  'Sciences Infirmières',
  'Médecine (spécifier la spécialité si possible, ex: Cardiologie, Pédiatrie)',
  'Ingénierie (Civile, Logicielle, Mécanique, Électrique, etc.)',
  'Architecture / Urbanisme',
  'Agriculture / Agronomie / Agroalimentaire',
  'Environnement / Développement Durable / RSE',
  'Tourisme / Hôtellerie / Événementiel',
  'Arts (Musique, Arts Visuels, Cinéma, Théâtre)',
  'Psychologie (Clinique, du Travail, Sociale)',
  'Sociologie / Anthropologie',
  'Sciences Politiques / Relations Internationales',
  'Logistique / Supply Chain Management',
  'Commerce International',
  'Qualité, Hygiène, Sécurité, Environnement (QHSE)',
  'Coaching (Professionnel, de Vie, Sportif)',
  'Recherche Scientifique (spécifier le domaine)',
  'Actuariat / Statistiques',
  'Gestion de Patrimoine',
  'E-commerce',
  'Animation 3D / Effets Spéciaux',
  'Biotechnologie',
  'Énergies Renouvelables',

  'Théologie (Systématique, Biblique, Pratique, Pastorale, Historique)',
  'Études Bibliques / Exégèse / Herméneutique',
  'Missiologie / Stratégies d\'Évangélisation et d\'Implantation d\'Églises',
  'Ministère Pastoral / Leadership Pastoral',
  'Leadership Chrétien / Développement du Leadership d\'Église',
  'Direction de Louange et Adoration / Musique d\'Église',
  'Ministère de la Musique (instrumental, vocal)',
  'Éducation Chrétienne / Direction d\'École du Dimanche / Pédagogie Religieuse',
  'Conseil Pastoral / Relation d\'Aide Chrétienne / Accompagnement Spirituel',
  'Diaconat / Ministère de la Compassion / Service Social Chrétien',
  'Administration Ecclésiastique / Gestion des Organisations Religieuses',
  'Communication d\'Église / Médias Chrétiens (Radio, TV, Web)',
  'Histoire de l\'Église / Patristique',
  'Apologétique Chrétienne',
  'Formation Spirituelle / Discipulat',
  'Ministère auprès des Enfants et des Adolescents',
  'Ministère auprès des Jeunes Adultes / Étudiants',
  'Ministère auprès des Familles / Conseil Conjugal et Familial Chrétien',
  'Ministère auprès des Aînés',
  'Aumônerie (Hospitalière, Carcérale, Militaire, Scolaire, d\'Entreprise)',
  'Gestion de Projets Humanitaires Chrétiens / Développement Communautaire',
  'Liturgie / Culte et Célébrations',
  'Prédication / Homilétique',
  'Droit Canonique / Droit Ecclésiastique',
  'Gestion Financière d\'Église / Levée de Fonds',
  'Technologie et Innovation pour l\'Église (Streaming, Applications, etc.)',
  'Traduction Biblique / Linguistique Biblique',
  'Ministère Interculturel / Mission Transculturelle',
  'Résolution de Conflits dans l\'Église',
  'Éthique Chrétienne (Bioéthique, Éthique Sociale)',
  'Animation de Petits Groupes / Cellules de prière',
  'Mentorat et Coaching Chrétien',
  'Ministère de la Guérison et de la Délivrance (selon les confessions)',
  'Études sur les Religions du Monde (perspective chrétienne)',
  'Rédaction et Édition de Contenu Chrétien (livres, articles, blogs)'
];

export const categories = [
  // Catégories spécifiques aux serviteurs de Dieu (maintenues pour référence)
  'Développement Personnel',
  'Leadership Chrétien',
  'Théologie & Doctrine',
  'Exégèse & Herméneutique',
  'Homilétique & Prédication',
  'Pastorale & Conseil',
  'Mission & Évangélisation',
  'Adoration & Louange',
  'Gestion du Ministère',
  'Finances & Dîme',
  'Droit Canonique & Éthique',
  'Histoire de l\'Église',
  'Apologétique',
  'Relations Interpersonnelles',
  'Communication & Médias',
  'Compétences Numériques',
  'Santé Mentale & Bien-être',
  'Action Sociale & Diaconie',
  'Famille & Mariage',
  'Ministère des Enfants & Jeunesse',
  'Discipolat',
  'Langues Bibliques',
  'Liturgie & Célébration',
  'Gestion de Projet (Ministériel)',
  'Innovation & Vision',
  'Planification Stratégique pour l\'Église',
  'Gestion des Conflits',
  'Encouragement & Motivation',
  'Discipline Ecclésiastique',
  'Intercession & Prière',
  'Prophétie & Discernement Spirituel',
  'Conduite de Petits Groupes',
  'Fondements de la Foi',
  'Théologie Systématique',
  'Théologie Pratique',
  'Missiologie Contextuelle',
  'Leadership Serviteur',
  'Gestion du Temps & Productivité',
  'Mentorat & Coaching Spirituel',
  'Organisation d\'Événements (Chrétiens)',
  'Sécurité & Protection (Église/Communauté)',
  'Art & Créativité dans le Culte',
  'Interprétation des Songes & Visions',
  'Libération & Guérison',
  'Rédaction de Sermons & Études Bibliques',
  'Gestion de Crise (Pastorale)',
  'Implémentation de Programmes Communautaires',
  'Cultiver une Vie de Sainteté',
  'Ministère auprès des Personnes Âgées',
  'Accompagnement du Deuil',
  'Stratégies de Croissance de l\'Église',
  'Impact Social Chrétien',
  'Théologie de la Prospérité (Analyse Critique)',
  'Gouvernance d\'Église',

  // Nouvelles catégories plus générales
  'Développement Logiciel',
  'Science des Données',
  'Intelligence Artificielle',
  'Cybersécurité',
  'Marketing Digital',
  'Vente & Négociation',
  'Gestion de Projet (Général)',
  'Ressources Humaines',
  'Comptabilité & Fiscalité',
  'Entrepreneuriat',
  'Design Graphique',
  'Montage Vidéo',
  'Photographie',
  'Musique',
  'Écriture & Rédaction',
  'Langues Étrangères',
  'Bien-être & Sport',
  'Cuisine & Gastronomie',
  'Artisanat & Bricolage',
  'Éducation & Pédagogie',
  'Environnement & Durabilité',
  'Droit & Législation (Général)',
  'Recherche Scientifique',
  'Relations Publiques',
  'Logistique & Chaîne d\'Approvisionnement',
  'Service Client',
  'Développement Durable',
  'Innovation & Créativité',
  'Finances Personnelles',
  'Investissement',
  'Immobilier',
  'Commerce International',
  'Psychologie',
  'Sociologie',
  'Histoire Générale',
  'Philosophie',
  'Technologie Blockchain',
  'Robotique',
  'Impression 3D',
  'Réalité Virtuelle & Augmentée',
  'Développement Mobile',
  'Sécurité au Travail',
  'Gestion de Qualité',
  'Audit',
  'Branding Personnel',
  'Rédaction de Contenu',
  'SEO & SEM',
  'Publicité en Ligne',
  'Analytique Web',
  'Gestion de Communauté',
  'Création de Podcasts',
  'Animation',
  'Développement de Jeux Vidéo',
  'Maintenance Informatique',
  'Réseaux Informatiques',
  'Cloud Computing',
  'Big Data',
  'Ethique des Affaires',
  'Développement Durable',
  'Planification Urbaine',
  'Agriculture & Agroalimentaire',
  'Tourisme & Hôtellerie',
  'Mode & Textile',
  'Journalisme',
  'Traduction & Interprétation',
];