"""Migration created

Revision ID: 0b42953eaf32
Revises: 5561ebd89a37
Create Date: 2025-06-07 22:15:07.725018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b42953eaf32'
down_revision = '5561ebd89a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_lessons', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('course_lessons', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_lessons', 'updated_at')
    op.drop_column('course_lessons', 'created_at')
    # ### end Alembic commands ###
