"""Migration update

Revision ID: 376154e6df8f
Revises: 722426fa7990
Create Date: 2025-06-08 14:47:04.021288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '376154e6df8f'
down_revision = '722426fa7990'
branch_labels = None
depends_on = None


def upgrade():
    # Étape 1 : Ajouter la colonne `enrolled_at` avec NULL autorisé
    op.add_column('enrollments', sa.Column('enrolled_at', sa.DateTime(), nullable=True))

    # Étape 2 : Mettre une valeur par défaut pour les lignes existantes
    op.execute("UPDATE enrollments SET enrolled_at = NOW() WHERE enrolled_at IS NULL")

    # Étape 3 : Rendre la colonne NOT NULL
    op.alter_column('enrollments', 'enrolled_at', nullable=False)

    # Ajouter les autres colonnes (les JSON et autres), ici on peut les mettre directement si elles ne posent pas problème
    op.add_column('enrollments', sa.Column('progress_percentage', sa.Float(), nullable=False, server_default="0"))
    op.add_column('enrollments', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('enrollments', sa.Column('completed_lessons', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('enrollments', sa.Column('completed_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('enrollments', sa.Column('test_attempts', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('enrollments', sa.Column('test_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))

    # Mettre à jour les contraintes de clé étrangère
    op.drop_constraint(op.f('enrollments_course_id_fkey'), 'enrollments', type_='foreignkey')
    op.drop_constraint(op.f('enrollments_user_id_fkey'), 'enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'enrollments', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'enrollments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_foreign_key(op.f('enrollments_user_id_fkey'), 'enrollments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('enrollments_course_id_fkey'), 'enrollments', 'courses', ['course_id'], ['id'])
    op.drop_column('enrollments', 'test_scores')
    op.drop_column('enrollments', 'test_attempts')
    op.drop_column('enrollments', 'completed_sections')
    op.drop_column('enrollments', 'completed_lessons')
    op.drop_column('enrollments', 'completed_at')
    op.drop_column('enrollments', 'progress_percentage')
    op.drop_column('enrollments', 'enrolled_at')
    # ### end Alembic commands ###
