"""Migration category

Revision ID: 5561ebd89a37
Revises: 7fe3e10b1450
Create Date: 2025-06-06 21:51:06.471051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5561ebd89a37'
down_revision = '7fe3e10b1450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'level')
    # ### end Alembic commands ###
