"""Migration update

Revision ID: 722426fa7990
Revises: 0b42953eaf32
Create Date: 2025-06-08 07:37:41.460003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722426fa7990'
down_revision = '0b42953eaf32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
