"""Migration category

Revision ID: 7fe3e10b1450
Revises: 6f7fd841dc2c
Create Date: 2025-06-06 21:44:14.691970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe3e10b1450'
down_revision = '6f7fd841dc2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'category')
    # ### end Alembic commands ###
