# Generated by Django 5.1.15 on 2026-05-02 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("short_description", models.TextField(blank=True, null=True)),
                ("image_url", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("price", models.FloatField(blank=True, default=0.0, null=True)),
                ("is_free", models.BooleanField(default=False)),
                ("objectives", models.JSONField(blank=True, null=True)),
                ("prerequisites", models.JSONField(blank=True, null=True)),
                (
                    "points_required_for_certificate",
                    models.IntegerField(blank=True, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=128, null=True)),
                ("level", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        db_column="instructor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructed_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "courses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("order", models.IntegerField()),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("video", "Video"),
                            ("quiz", "Quiz"),
                        ],
                        default="text",
                        max_length=16,
                    ),
                ),
                ("video_url", models.CharField(blank=True, max_length=512, null=True)),
                ("text_content", models.TextField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        db_column="course_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "db_table": "course_sections",
                "ordering": ["course_id", "order"],
            },
        ),
        migrations.CreateModel(
            name="CourseLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("text", "Text"),
                            ("quiz", "Quiz"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content_body", models.TextField(blank=True, null=True)),
                ("duration", models.CharField(blank=True, max_length=64, null=True)),
                ("order", models.IntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        db_column="section_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.coursesection",
                    ),
                ),
            ],
            options={
                "db_table": "course_lessons",
                "ordering": ["section_id", "order"],
            },
        ),
        migrations.CreateModel(
            name="CourseTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("passing_score", models.IntegerField(blank=True, null=True)),
                ("max_attempts", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "section",
                    models.OneToOneField(
                        blank=True,
                        db_column="section_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test",
                        to="courses.coursesection",
                    ),
                ),
            ],
            options={
                "db_table": "course_tests",
            },
        ),
        migrations.CreateModel(
            name="TestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[("multiple_choice", "Multiple choice")],
                        default="multiple_choice",
                        max_length=32,
                    ),
                ),
                ("options", models.JSONField(blank=True, null=True)),
                ("correct_answer_data", models.JSONField(blank=True, null=True)),
                ("points", models.IntegerField(default=1)),
                (
                    "test",
                    models.ForeignKey(
                        db_column="test_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="courses.coursetest",
                    ),
                ),
            ],
            options={
                "db_table": "test_questions",
            },
        ),
    ]
