# Generated by Django 5.1.15 on 2026-05-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courselesson",
            name="video_url",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
