# Generated by Django 5.1.15 on 2026-05-02 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveSession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("scheduled_for", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                        ],
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                ("actual_started_at", models.DateTimeField(blank=True, null=True)),
                ("actual_ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "meeting_room_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        db_column="course_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_sessions",
                        to="courses.course",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        db_column="host_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_live_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "live_sessions",
                "ordering": ["-scheduled_for"],
            },
        ),
        migrations.CreateModel(
            name="LiveSessionAttendance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("first_joined_at", models.DateTimeField(blank=True, null=True)),
                ("last_joined_at", models.DateTimeField(blank=True, null=True)),
                ("last_left_at", models.DateTimeField(blank=True, null=True)),
                ("total_duration_seconds", models.IntegerField(default=0)),
                ("join_count", models.IntegerField(default=0)),
                ("is_present", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "live_session",
                    models.ForeignKey(
                        db_column="live_session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="live_sessions.livesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_session_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "live_session_attendances",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("live_session", "user"),
                        name="uq_live_session_attendance_session_user",
                    )
                ],
            },
        ),
    ]
