# Generated by Django 5.1.15 on 2026-05-03 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        ("courses", "0002_courselesson_video_url"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="content",
            field=models.ForeignKey(
                blank=True,
                db_column="content_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="content.content",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                db_column="course_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="courses.course",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("content__isnull", True), ("course__isnull", False)),
                    models.Q(("content__isnull", False), ("course__isnull", True)),
                    _connector="OR",
                ),
                name="payment_target_exactly_one",
            ),
        ),
    ]
